targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          exclude:
            - "**.worker.dart"
        release_options:
          dart2js_args:
            - -O3